# Generated by Django 2.1.7 on 2019-06-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userNet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.FileField(upload_to='usermodels')),
                ('channels', models.CharField(max_length=10)),
                ('windowSize', models.CharField(max_length=20)),
            ],
        ),
    ]
