# Generated by Django 2.1.7 on 2019-06-27 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newupload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernet',
            old_name='model_name',
            new_name='file',
        ),
        migrations.AddField(
            model_name='usernet',
            name='link',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernet',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
