# Generated by Django 2.1.7 on 2019-07-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'Convolutional'), ('2', 'Linear')], max_length=1)),
                ('input', models.IntegerField()),
                ('output', models.IntegerField()),
                ('kernel', models.IntegerField()),
                ('stride', models.IntegerField()),
                ('padding', models.IntegerField()),
                ('pool_kernel', models.IntegerField()),
                ('pool_stride', models.IntegerField()),
                ('out_dim', models.IntegerField()),
            ],
        ),
    ]
