# Generated by Django 2.1.7 on 2019-06-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newupload', '0002_auto_20190627_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernet',
            name='file',
        ),
    ]
