# Generated by Django 2.1.7 on 2019-07-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newupload', '0003_auto_20190703_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='type',
        ),
    ]
