# Generated by Django 2.1.7 on 2019-06-27 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newupload', '0003_remove_usernet_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernet',
            old_name='windowSize',
            new_name='sampleFrequency',
        ),
        migrations.AddField(
            model_name='usernet',
            name='windowSec',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
