# Generated by Django 2.1.7 on 2019-07-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newupload', '0004_auto_20190627_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('seizureStart', models.IntegerField()),
                ('seizureEnd', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usernet',
            name='channels',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='sampleFrequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='windowSec',
            field=models.IntegerField(),
        ),
    ]
