# Generated by Django 2.1.7 on 2019-07-01 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newupload', '0005_auto_20190701_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='channels',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfiles',
            name='nSignal',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfiles',
            name='sampleFrequency',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
